BCMWeb/Controllers/EventosController.cs
using BCMWeb.Models;
using DevExpress.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BCMWeb.Controllers
{

    [Authorize]
    public class EventosController : Controller
    {

        [SessionExpire]
        [HandleError]
        public ActionResult Index(long IdModulo)
        {
            FirstModuloSelected firstModulo = Metodos.GetFirstUserModulo(IdModulo);

            return RedirectToAction(firstModulo.Action, firstModulo.Controller, new { modId = firstModulo.IdModulo });
        }
        [SessionExpire]
        [HandleError]
        public ActionResult Dispositivos(long modId)
        {

            Session["modId"] = modId;

            string _modId = modId.ToString();
            int IdTipoDocumento = int.Parse(_modId.Substring(0, (_modId.Length == 7 ? 1 : 2)));

            long IdModulo = IdTipoDocumento * 1000000;

            DispositivosEmpresaModel model = new DispositivosEmpresaModel
            {
                IdModulo = IdModulo,
                IdModuloActual = modId,
                Perfil = Metodos.GetPerfilData(),
                PageTitle = Metodos.GetModuloName(modId),
                returnPage = Url.Action("Index", "Documento", new { IdModulo }),
            };

            ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);
            Auditoria.RegistarAccion(eTipoAccion.ConsultarDispositivos);
            Session["GridViewData"] = Metodos.GetDispositivosMoviles();
            return View(model);
        }
        [SessionExpire]
        [HandleError]
        [HttpPost]
        public ActionResult ExportDispositivos()
        {
            string _modId = Session["modId"].ToString();
            long modId = long.Parse(_modId);
            int IdTipoDocumento = int.Parse(_modId.Substring(0, (_modId.Length == 7 ? 1 : 2)));

            long IdModulo = IdTipoDocumento * 1000000;

            //model.IdModulo = IdModulo;
            //model.IdModuloActual = modId;
            //model.Perfil = Metodos.GetPerfilData();
            //model.PageTitle = Metodos.GetModuloName(modId);
            //ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);

            Session["GridViewData"] = Metodos.GetDispositivosMoviles();
            return GridViewExportIniciativas.FormatConditionsExportFormatsInfo[GridViewExportFormat.Xlsx](GridViewExportIniciativas.FormatConditionsExportGridViewSettings, Metodos.GetDispositivosMoviles());

        }
        [SessionExpire]
        [HandleError]
        public ActionResult DispositivosPartialView()
        {
            Session["GridViewData"] = Metodos.GetDispositivosMoviles();
            return PartialView("DispositivosPartialView");
        }
        [SessionExpire]
        [HandleError]
        [ValidateInput(false)]
        public ActionResult ConexionesPartial(string IdDispositivo)
        {
            if (IdDispositivo != null)
                Session["IdDispositivo"] = IdDispositivo;
            Session["gvConexionesData"] = Metodos.GetConexionesDispositivo(IdDispositivo);
            return PartialView("ConexionesPartial");
        }

        [SessionExpire]
        [HandleError]
        public ActionResult Activar(long modId)
        {

            Session["modId"] = modId;

            string _modId = modId.ToString();
            int IdTipoDocumento = int.Parse(_modId.Substring(0, (_modId.Length == 7 ? 1 : 2)));

            long IdModulo = IdTipoDocumento * 1000000;
            Nullable<long> _idSubmodulo = Metodos.GetEscenariosEmpresa().FirstOrDefault().Id;

            EventoRegistroEmpresaModel model = new EventoRegistroEmpresaModel
            {
                IdSubmoduloSelected = _idSubmodulo ?? 0,
                IdModulo = IdModulo,
                IdModuloActual = modId,
                Perfil = Metodos.GetPerfilData(),
                PageTitle = Metodos.GetModuloName(modId),
                Dispositivos = Metodos.GetDispositivosMovilEvento(_idSubmodulo ?? 0),
            };

            ViewBag.SelectAllCheckBoxMode = (model.Dispositivos.Count(x => x.FechaEnvio == null) == 0 ? GridViewSelectAllCheckBoxMode.None : GridViewSelectAllCheckBoxMode.AllPages);
            ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);
            Auditoria.RegistarAccion(eTipoAccion.ConsultarDispositivos);
            return View(model);
        }
        [SessionExpire]
        [HandleError]
        [HttpPost]
        public ActionResult Activar(EventoRegistroEmpresaModel model)
        {

            string _modId = Session["modId"].ToString();
            long modId = long.Parse(_modId);
            int IdTipoDocumento = int.Parse(_modId.Substring(0, (_modId.Length == 7 ? 1 : 2)));

            long IdModulo = IdTipoDocumento * 1000000;

            model.IdModulo = IdModulo;
            model.IdModuloActual = modId;
            model.Perfil = Metodos.GetPerfilData();
            model.PageTitle = Metodos.GetModuloName(modId);
            model.Dispositivos = Metodos.GetDispositivosMovilEvento(model.IdSubmoduloSelected);

            ViewBag.SelectAllCheckBoxMode = (model.Dispositivos.Count(x => x.FechaEnvio == null) == 0 ? GridViewSelectAllCheckBoxMode.None : GridViewSelectAllCheckBoxMode.AllPages);
            ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);
            return View(model);
        }
        [SessionExpire]
        [HandleError]
        public ActionResult ComboBoxEvento(long Id)
        {
            EventoEmpresaModel model = new EventoEmpresaModel();
            model.IdSubmoduloSelected = Id;
            return PartialView(model);
        }
        [SessionExpire]
        [HandleError]
        public ActionResult DispEventPartialView()
        {
            
            string _selectedIDs = Request.Params["selectedIDs"];
            string _idModuloSelected = Request.Params["idModuloSelected"];

            string _modId = Session["modId"].ToString();
            long modId = long.Parse(_modId);
            int IdTipoDocumento = int.Parse(_modId.Substring(0, (_modId.Length == 7 ? 1 : 2)));

            long IdModulo = IdTipoDocumento * 1000000;
            Nullable<long> _idSubmodulo = long.Parse(_idModuloSelected);

            EventoRegistroEmpresaModel model = new EventoRegistroEmpresaModel
            {
                IdSubmoduloSelected = _idSubmodulo ?? 0,
                IdModulo = IdModulo,
                IdModuloActual = modId,
                Perfil = Metodos.GetPerfilData(),
                PageTitle = Metodos.GetModuloName(modId),
                Dispositivos = Metodos.GetDispositivosMovilEvento(_idSubmodulo ?? 0),
            };

            ViewBag.SelectAllCheckBoxMode = (model.Dispositivos.Count(x => x.FechaEnvio == null) == 0 ? GridViewSelectAllCheckBoxMode.None : GridViewSelectAllCheckBoxMode.AllPages);
            ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);

            return PartialView(model);
        }
        [SessionExpire]
        [HandleError]
        public ActionResult SaveEvento(string IDs, long idSubmodulo)
        {
            Metodos.InsertEvento(idSubmodulo, IDs);

            string _modId = Session["modId"].ToString();
            long modId = long.Parse(_modId);

            return RedirectToAction("Activar", new { modId });
        }
    }
}

BCMWeb/Views/Eventos/Activar.cshtml
@using BCMWeb.Models

@model EventoEmpresaModel

<script type="text/javascript">
    var selectedIDs;

    function onSelectAllClick() {
        alert('entra');
        gvDispositivos.SelectRows();
    }
    function onClearSelectionClick() {
        gvDispositivos.UnselectRows();
    }

    function OnGridViewInit() {
        UpdateTitlePanel();
    }
    function OnGridViewSelectionChanged(s, e) {
        UpdateTitlePanel();
        s.GetSelectedFieldValues("Id", GetSelectedFieldValuesCallback);
    }
    function GetSelectedFieldValuesCallback(values) {
        //Capture all selected keys
        selectedIDs = values.join(',');
    }
    function OnGridViewBeginCallback(s, e) {
        // e.customArgs["selectAllMode"] = selectAllMode.GetText();
        lp.Show();
        e.customArgs["selectedIDs"] = selectedIDs;
        e.customArgs["idModuloSelected"] = $("#IdSubmoduloSelected").val();
    }
    function OnGridViewEndCallback() {
        UpdateTitlePanel();
        lp.Hide();
    }
    function getSelectedRowCount() {
        $("#countSelected").val(gvDispositivos.GetSelectedRowCount());
    }
    function UpdateTitlePanel() {
        var selectedFilteredRowCount = GetSelectedFilteredRowCount();

        var text = "Total rows selected: <b>" + gvDispositivos.GetSelectedRowCount() + "</b>. ";
        var hiddenSelectedRowCount = gvDispositivos.GetSelectedRowCount() - GetSelectedFilteredRowCount();
        if (hiddenSelectedRowCount > 0)
            text += "Selected rows hidden by the applied filter: <b>" + hiddenSelectedRowCount + "</b>.";
        text += "<br />";
        lblInfo.SetText(text);
        $("#countSelected").val(gvDispositivos.GetSelectedRowCount());

        var isAllPages = "AllPages";
        SetElementVisibility(btnSave, $("#countSelected").val() > 0);
        SetElementVisibility(lnkSelectAllRows, !isAllPages && gvDispositivos.cpVisibleRowCount > selectedFilteredRowCount);
        SetElementVisibility(lnkClearSelection, !isAllPages && gvDispositivos.GetSelectedRowCount() > 0);
    }
    function GetSelectedFilteredRowCount() {
        return gvDispositivos.cpFilteredRowCountWithoutPage + gvDispositivos.GetSelectedKeysOnPage().length;
    }
    function SetElementVisibility(id, visible) {
        visible ? id.SetVisible(true) : id.SetVisible(false)
    }
    function OnSubmitClick(s, e) {
        //Write all selected keys to hidden input. Pass them on post action.
        lp.Show()
        var selectedIds = selectedIDs;
        document.location = "@Url.Action("SaveEvento", "Eventos")?IDs=" + selectedIDs + "&idSubmodulo="  + $("#IdSubmoduloSelected").val();
    }
</script>

@section LeftPanel {
    @Html.DevExpress().Panel(settings =>
{
    settings.Name = "LeftPane";
    settings.FixedPosition = PanelFixedPosition.WindowLeft;
    settings.Collapsible = true;
    settings.SettingsAdaptivity.CollapseAtWindowInnerWidth = 1023;
    settings.ControlStyle.CssClass = "leftPane";
    settings.Styles.Panel.CssClass = "panel";
    settings.SetContent(() =>
    {
        Html.RenderPartial("ContentLeftPartialView");
    });
}).GetHtml()
}

@using (Html.BeginForm("Activar", "Eventos", FormMethod.Post, htmlAttributes: new { id = "EventoForm" }))
{
    @Html.HiddenFor(m => m.IdSubmoduloSelected)
    @Html.HiddenFor(m => m.countSelected)
    @Html.HiddenFor(m => m.selectedIds);
    @Html.HiddenFor(m => m.isSaving);

    @Html.Partial("ComboBoxEvento")

<div class="titleContainer BottomLargeMargin" style="margin-top: 20px; margin-bottom: 25px; float:right;">
    @Html.DevExpress().Label(settingslbl => {
        settingslbl.Name = "lblInfo";
        settingslbl.Properties.EnableClientSideAPI = true;
    }).GetHtml()
    @Html.DevExpress().HyperLink(settings => {
   settings.Name = "lnkSelectAllRows";
   settings.Properties.Text = Resources.DispositivoResource.labelLnkSelectAllRows;
   settings.ControlStyle.Cursor = "Pointer";
   settings.Properties.EnableClientSideAPI = true;
   settings.ClientVisible = false;
   settings.Properties.ClientSideEvents.Click = "onSelectAllClick";
}).GetHtml()
    @Html.DevExpress().HyperLink(settings => {
   settings.Name = "lnkClearSelection";
   settings.Properties.Text = Resources.DispositivoResource.labelLnkClearSelection;
   settings.ControlStyle.Cursor = "Pointer";
   settings.Properties.EnableClientSideAPI = true;
   settings.ClientVisible = false;
   settings.Properties.ClientSideEvents.Click = "onClearSelectionClick";
}).GetHtml()
</div>

    @Html.Partial("DispEventPartialView", Model)

    <div class="titleContainer BottomLargeMargin" style="margin-top: 20px; margin-bottom: 25px; float:right;">
        @Html.DevExpress().Button(
        btnSettings =>
        {
        btnSettings.Name = "btnCancel";
        btnSettings.Text = Resources.BCMWebPublic.captionButtonCancel;
        btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
        btnSettings.ClientSideEvents.Click = "function(s, e) { lp.Show(); document.location='" + Model.returnPage + "' }";
        }).GetHtml()
        @Html.DevExpress().Button(
        btnSettings =>
        {
            btnSettings.Name = "btnSave";
            btnSettings.Text = Resources.BCMWebPublic.captionButtonSave;
            btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
            btnSettings.ClientVisible = (Model.countSelected > 0);
            btnSettings.UseSubmitBehavior = false;
            btnSettings.ClientSideEvents.Click = "OnSubmitClick";
        }).GetHtml()
    </div>
}

BCMWeb/Views/Eventos/ComboBoxEmpresa.cshtml
@using BCMWeb
@using BCMWeb.Models

@model UsuariosModel

@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "cbxEmpresa";
        settings.Width = Unit.Percentage(50);
        settings.SelectedIndex = 0;
        settings.CallbackRouteValues = new { Controller = "Eventos", Action = "ComboBoxEmpresa", IdEmpresa = Model.IdEmpresaSelected };
        settings.Properties.CallbackPageSize = 15;
        settings.Properties.Caption = Resources.EmpresaResource.captionEmpresa;
        settings.Properties.DropDownStyle = DropDownStyle.DropDownList;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.TextFormatString = "{0}";
        settings.Properties.TextField = "NombreComercial";
        settings.Properties.ValueField = "IdEmpresa";
        settings.Properties.ValueType = typeof(System.Int64);
        settings.Properties.ItemStyle.SelectedStyle.CssClass = "selectedItem";
        settings.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Never;
        settings.Properties.ClientSideEvents.BeginCallback = "function (s,e) { lp.Show();}";
        settings.Properties.ClientSideEvents.EndCallback = "function (s,e) { lp.Hide();}";
        //settings.Properties.ClientSideEvents.SelectedIndexChanged = "function (s,e) { lp.Show(); $(\"#IdEmpresaSelected\").val(cbxEmpresa.GetValue()); document.forms[\"EmpresaForm\"].submit(); }";
        settings.Properties.ClientSideEvents.SelectedIndexChanged = "function (s,e) { lp.Show(); $(\"#IdEmpresaSelected\").val(cbxEmpresa.GetValue()); document.forms[\"EmpresaForm\"].submit(); }";
    }
).BindList(Metodos.GetEmpresasUsuario()).Bind(Model.IdEmpresaSelected).GetHtml()

BCMWeb/Views/Eventos/ComboBoxEvento.cshtml
@using BCMWeb
@using BCMWeb.Models

@model EventoEmpresaModel

@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "cbxEvento";
        settings.Width = Unit.Percentage(50);
        settings.SelectedIndex = 0;
        settings.CallbackRouteValues = new { Controller = "Eventos", Action = "ComboBoxEvento", IdSubModulo = Model.IdSubmoduloSelected };
        settings.Properties.CallbackPageSize = 15;
        settings.Properties.Caption = Resources.DispositivoResource.labelComboEvento;
        settings.Properties.DropDownStyle = DropDownStyle.DropDownList;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.TextFormatString = "{0}";
        settings.Properties.TextField = "Descripcion";
        settings.Properties.ValueField = "Id";
        settings.Properties.ValueType = typeof(System.Int64);
        settings.Properties.ItemStyle.SelectedStyle.CssClass = "selectedItem";
        settings.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Never;
        settings.Properties.ClientSideEvents.BeginCallback = "function (s,e) { lp.Show();}";
        settings.Properties.ClientSideEvents.EndCallback = "function (s,e) { lp.Hide();}";
        settings.Properties.ClientSideEvents.SelectedIndexChanged = "function (s,e) { lp.Show(); $(\"#IdSubmoduloSelected\").val(cbxEvento.GetValue()); document.forms[\"EventoForm\"].submit(); }";
    }
).BindList(Metodos.GetEscenariosEmpresa()).Bind(Model.IdSubmoduloSelected).GetHtml()

BCMWeb/Views/Eventos/ConexionesPartial.cshtml
@using BCMWeb
@using DevExpress.Data;

@{

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();

    var grid = Html.DevExpress().GridView(
        settings =>
        {
            settings.Name = "gvConexiones";
            settings.CallbackRouteValues = new { Controller = "Eventos", Action = "ConexionesPartial" };
            settings.SettingsBehavior.ConfirmDelete = true;
            settings.Width = Unit.Percentage(100);
            settings.Settings.VerticalScrollableHeight = 80;
            settings.Settings.HorizontalScrollBarMode = ScrollBarMode.Visible;
            settings.Settings.VerticalScrollBarMode = ScrollBarMode.Auto;
            settings.Caption = Resources.DispositivoResource.gvConexionesTitle;
            settings.Styles.TitlePanel.Font.Bold = true;
            settings.SettingsPager.Mode = GridViewPagerMode.ShowAllRecords;
            settings.SettingsLoadingPanel.Mode = GridViewLoadingPanelMode.Disabled;
            settings.ClientSideEvents.BeginCallback = "function (s,e) { lp.Show(); }";
            settings.ClientSideEvents.EndCallback = "function (s,e) { lp.Hide(); }";

            settings.Settings.ShowFilterRow = true;
            settings.Settings.ShowFilterRowMenu = true;
            settings.Settings.ShowFooter = true;

            settings.CommandColumn.Visible = false;

            settings.Columns.Add(c =>
            {
                c.FieldName = "FechaConexion";
                c.Caption = Resources.DispositivoResource.labelFechaConexion;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                c.FooterCellStyle.HorizontalAlign = HorizontalAlign.Center;
                c.FixedStyle = GridViewColumnFixedStyle.Left;
                c.Width = Unit.Percentage(20);
            });
            settings.Columns.Add(c =>
            {
                c.FieldName = "Empresa";
                c.Caption = Resources.DispositivoResource.labelEmpresa;
                c.FixedStyle = GridViewColumnFixedStyle.Left;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Left;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.Width = Unit.Percentage(60);
                c.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
            });
            settings.Columns.Add(c =>
            {
                c.FieldName = "DireccionIP";
                c.Caption = Resources.DispositivoResource.labelDireccionIP;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.Width = Unit.Percentage(20);
                c.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
            });
        });
}
@grid.Bind(Session["gvConexionesData"]).GetHtml()

BCMWeb/Views/Eventos/ContentLeftPartialView.cshtml
@using BCMWeb.Models

@model ModulosUserModel

<script type="text/javascript">
    function itemMenuClick(s, e) {
        if (e.item.items.length == 0) {
            var _href = e.htmlElement.href;
            var spl = _href.split("=");
            var lng = spl.length;
            var modId = spl[lng - 1]

            if (modId == 99010100) {
                lp.SetText('@Html.Raw(Resources.BCMWebPublic.labelLoadPanelAprobacion)');
            }
            else {
                lp.SetText('@Html.Raw(Resources.BCMWebPublic.labelLoadPanel)');
            }
            lp.Show();
        }
    }
</script>

<div class="leftPanel" style="margin-bottom: 50px;">
    <table>
        <tr>
            <td>
                @Html.DevExpress().Button(b =>
                {
                    b.Name = "botReturn";
                    b.Text = Resources.BCMWebPublic.botReturnText;
                    b.ClientSideEvents.Click = "function(s, e) { lp.Show(); document.location='" + DevExpressHelper.GetUrl(new { Controller = "Menu", Action = "Index" }) + "' }";
                }).GetHtml()
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <table>
                    <tr>
                        <td class="ModuloHeader">
                            <div>
                                @Html.DisplayFor(m => m.ModuloActual)
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>
                            @Html.DevExpress().Menu(s =>
                            {
                                s.Name = "menuOpciones";
                                s.Width = Unit.Percentage(100);
                                s.ItemAutoWidth = false;
                                s.Styles.Item.Font.Size = FontUnit.Small;
                                s.Styles.Item.Wrap = DefaultBoolean.True;
                                s.Styles.SubMenuItem.Font.Size = FontUnit.Small;
                                s.Styles.SubMenuItem.Wrap = DefaultBoolean.True;
                                s.Styles.SubMenuItem.Width = Unit.Pixel(150);
                                s.Orientation = Orientation.Vertical;
                                s.ShowPopOutImages = DefaultBoolean.False;
                                s.ControlStyle.HorizontalAlign = HorizontalAlign.Center;
                                s.EnableAdaptivity = true;
                                s.ClientSideEvents.ItemClick = "itemMenuClick";
                            }).Bind(Model.SubModulos).GetHtml()
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

BCMWeb/Views/Eventos/Dispositivos.cshtml
@using BCMWeb
@using BCMWeb.Models

@model DispositivosEmpresaModel

@section LeftPanel {
    @Html.DevExpress().Panel(settings =>
   {
       settings.Name = "LeftPane";
       settings.FixedPosition = PanelFixedPosition.WindowLeft;
       settings.Collapsible = true;
       settings.SettingsAdaptivity.CollapseAtWindowInnerWidth = 1023;
       settings.ControlStyle.CssClass = "leftPane";
       settings.Styles.Panel.CssClass = "panel";
       settings.SetContent(() =>
       {
           Html.RenderPartial("ContentLeftPartialView");
       });
   }).GetHtml()
}

<script type="text/javascript">
    //function OnButtonClick(s, e, startUrl, Id) {
    //    StartActionOnServer(startUrl, Id);
    //}
    //function StartActionOnServer(startUrl, Id) {
    //    lp.Show();
    //    $.ajax({
    //        type: 'POST',
    //        url: startUrl,
    //        dataType: 'json',
    //        data: {
    //            IdIniciativa: Id
    //        },
    //    }).done(ProgressCallbackComplete)
    //      .fail(CallbackError);
    //}
    //function ProgressCallbackComplete(data) {
    //    lp.Hide();
    //    //window.open('MyPDF.pdf', '_blank', 'fullscreen=yes'); return false;"
    //    window.open(data._rutaDocumento, '_blank', 'fullscreen=NO');
    //}
    function CallbackError() {
        lp.Hide();
        alert('Error haciendo callback en Dispositivos');
    }
</script>

@using (Html.BeginForm("ExportDispositivos", "Eventos", FormMethod.Post, htmlAttributes: new { id = "DispositivosForm" }))
{

    @Html.HiddenFor(m => m.IdModuloActual)

    <div style="float: right; margin-top: -25px;">
        @Html.DevExpress().Button(settings =>
        {
            settings.Name = "btExport";
            settings.Text = Resources.BCMWebPublic.stringExportExcel;
            settings.UseSubmitBehavior = true;
        }).GetHtml()
    </div>

    @Html.Partial("DispositivosPartialView", Session["GridViewData"])

}