BCMWeb/Controllers/PMTController.cs
using BCMWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BCMWeb.Controllers
{
    [Authorize]
    public class PMTController : Controller
    {
        [SessionExpire]
        [HandleError]
        public ActionResult Index(long IdClaseDocumento, long modId)
        {
            string _modId = modId.ToString();
            int IdTipoDocumento = int.Parse(_modId.Substring(0, (_modId.Length == 7 ? 1 : 2)));
            Session["IdClaseDocumento"] = IdClaseDocumento;
            Session["modId"] = modId;

            long IdModulo = IdTipoDocumento * 1000000;

            ProgramacionModel model = new ProgramacionModel();
            model.IdModuloActual = modId;
            model.IdModulo = IdModulo;
            model.PageTitle = Resources.BCMWebPublic.captionBotonMantenimientos;
            model.IdClaseDocumento = (int)IdClaseDocumento;
            model.returnPage = Url.Action("Index", "Documento", new { IdModulo = modId });
            model.IdEmpresa = long.Parse(Session["IdEmpresa"].ToString());
            ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);

            return View(model);
        }
        [SessionExpire]
        [HandleError]
        [HttpPost]
        public ActionResult ExportProgramacion(ProgramacionModel model)
        {
            string _modId = Session["modId"].ToString();
            long modId = long.Parse(_modId);
            int IdTipoDocumento = int.Parse(_modId.Substring(0, (_modId.Length == 7 ? 1 : 2)));

            long IdModulo = IdTipoDocumento * 1000000;

            model.IdModulo = IdModulo;
            model.IdModuloActual = modId;
            model.Perfil = Metodos.GetPerfilData();
            model.PageTitle = Metodos.GetModuloName(modId);
            ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);

            Session["GridViewData"] = Metodos.GetProgramaciones();
            return GridViewExportProgramaciones.FormatConditionsExportFormatsInfo[GridViewExportFormat.Xlsx](GridViewExportProgramaciones.FormatConditionsExportGridViewSettings, Metodos.GetProgramaciones());

        }
        [SessionExpire]
        [HandleError]
        public ActionResult ProgramacionPartialView()
        {
            return PartialView("ProgramacionPartialView");
        }
        //[SessionExpire]
        //[HandleError]
        //[HttpPost]
        //public ActionResult ProgramacionPartialView(ProgramacionModel model)
        //{
        //    return PartialView("ProgramacionPartialView");
        //}
        [SessionExpire]
        [HandleError]
        [HttpPost, ValidateInput(false)]
        public ActionResult EditProgramacionAddNewPartial(ProgramacionModel Programacion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string IdModuloProgramacion = Programacion.IdModuloProgramacion.ToString();
                    Programacion.IdClaseDocumento = int.Parse(Session["IdClaseDocumento"].ToString());
                    Programacion.IdTipoDocumento = int.Parse(IdModuloProgramacion.Substring(0, (IdModuloProgramacion.Length == 7 ? 1 : 2)));
                    Programacion.IdEmpresa = long.Parse(Session["IdEmpresa"].ToString());
                    Programacion.IdEstadoProgramacion = 1;
                    Programacion.IdTipoActualizacion = 1;
                    Metodos.InsertProgramacion(Programacion);
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
            {
                ViewData["EditError"] = Resources.ErrorPageResource.AllErrors;
                ViewData["EditableProgramacion"] = Programacion;
            }
            Session["GridViewData"] = Metodos.GetProgramaciones();
            return PartialView("ProgramacionPartialView", Metodos.GetProgramaciones());
        }
        [SessionExpire]
        [HandleError]
        [HttpPost, ValidateInput(false)]
        public ActionResult EditProgramacionUpdatePartial(ProgramacionModel Programacion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Metodos.UpdateProgramacion(Programacion);
                    Auditoria.RegistarProgramacion(eTipoAccion.ActualizarProgramacion, Programacion.IdProgramacion, Programacion.IdModuloProgramacion, string.Empty);
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
            {
                ViewData["EditError"] = Resources.ErrorPageResource.AllErrors;
                ViewData["EditableProgramacion"] = Programacion;
            }

            Session["GridViewData"] = Metodos.GetProgramaciones();
            return PartialView("ProgramacionPartialView", Metodos.GetProgramaciones());
        }
        [SessionExpire]
        [HandleError]
        [HttpPost, ValidateInput(false)]
        public ActionResult EditProgramacionDeletePartial(long IdProgramacion)
        {
            if (IdProgramacion > 0)
            {
                try
                {
                    Metodos.DeleteProgramacion(IdProgramacion);
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            Session["GridViewData"] = Metodos.GetProgramaciones();
            return PartialView("ProgramacionPartialView", Metodos.GetProgramaciones());
        }
        [SessionExpire]
        [HandleError]
        public ActionResult Documentos(long IdProgramacion)
        {
            //Session["IdClaseDocumento"] = IdClaseDocumento;
            //Session["modId"] = modId;

            //long IdModulo = IdTipoDocumento * 1000000;

            ProgramacionModel reg = Metodos.GetEditableProgramacion(IdProgramacion);
            //model.IdModuloActual = modId;
            //model.IdModulo = IdModulo;
            //model.PageTitle = Metodos.GetModuloName(modId);
            //model.IdClaseDocumento = (int)IdClaseDocumento;
            //model.returnPage = Url.Action("Index", "Documento", new { IdTipoDocumento, modId });
            //model.IdEmpresa = long.Parse(Session["IdEmpresa"].ToString());
            //ViewBag.Title = string.Format("{0} - {1}", model.PageTitle, Resources.BCMWebPublic.labelAppTitle);

            ProgramacionDocumentoModel model = new ProgramacionDocumentoModel
            {
                IdModulo = reg.IdModuloProgramacion,
            };

            return View(model);
        }
        [SessionExpire]
        [HandleError]
        [HttpPost]
        public ActionResult Documentos(ProgramacionDocumentoModel model)
        {
            return View(model);
        }
        [SessionExpire]
        [HandleError]
        public ActionResult Usuarios(long IdProgramacion)
        {
            ProgramacionUsuarioModel model = new ProgramacionUsuarioModel
            {

            };

            return View(model);
        }
        [SessionExpire]
        [HandleError]
        [HttpPost]
        public ActionResult Usuarios(ProgramacionUsuarioModel model)
        {
            return View(model);
        }
    }
}

BCMWeb/Views/PMT/Index.cshtml
@using BCMWeb
@using BCMWeb.Models

@model ProgramacionModel

<script type="text/javascript">
    function Modulo_Changed(s, e) {
        var IdModuloSelected = s.GetValue();
        gvProgramacionDocumento.PerformCallback();
        gvProgramacionUsuario.PerformCallback();
    }
</script>

@using (Html.BeginForm("ExportProgramacion", "PMT", FormMethod.Post, htmlAttributes: new { id = "ProgramacionesForm" }))
{

    @Html.HiddenFor(m => m.IdEmpresa)
    @Html.HiddenFor(m => m.IdModuloActual)
    @Html.HiddenFor(m => m.IdClaseDocumento)
    @Html.HiddenFor(m => m.IdProgramacion)

    <div style="margin-top: -25px; margin-bottom: 5px;">
        <div>
            @Html.DevExpress().Button(b =>
                {
                    b.Name = "botReturn";
                    b.Text = Resources.BCMWebPublic.botReturnText;
                    b.ClientSideEvents.Click = "function(s, e) { lp.Show(); document.location='" + Model.returnPage + "' }";
                }).GetHtml()
        </div>
        <div style="float: right; margin-top: -25px;">
            @Html.DevExpress().Button(settings =>
        {
            settings.Name = "btExport";
            settings.Text = Resources.BCMWebPublic.stringExportExcel;
            settings.UseSubmitBehavior = true;
        }).GetHtml()
        </div>
    </div>

    @Html.Partial("ProgramacionPartialView")

}

BCMWeb/Views/PMT/ProgramacionPartialView.cshtml
@using BCMWeb;
@using BCMWeb.Models;
@using DevExpress.Data;

@{

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();

    var grid = Html.DevExpress().GridView<ProgramacionModel>(
        settings =>
        {
            settings.Name = "gvProgramacion";
            settings.KeyFieldName = "IdProgramacion";
            settings.CallbackRouteValues = new { Controller = "PMT", Action = "ProgramacionPartialView" };
            settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "PMT", Action = "EditProgramacionAddNewPartial" };
            settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "PMT", Action = "EditProgramacionUpdatePartial" };
            settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "PMT", Action = "EditProgramacionDeletePartial" };
            settings.SettingsEditing.Mode = GridViewEditingMode.PopupEditForm;
            settings.SettingsBehavior.ConfirmDelete = true;
            settings.Width = Unit.Percentage(100);
            settings.Settings.VerticalScrollableHeight = 325;
            settings.Settings.HorizontalScrollBarMode = ScrollBarMode.Hidden;
            settings.Settings.VerticalScrollBarMode = ScrollBarMode.Auto;
            settings.Styles.TitlePanel.Font.Bold = true;
            settings.SettingsPager.Mode = GridViewPagerMode.ShowAllRecords;
            settings.SettingsLoadingPanel.Mode = GridViewLoadingPanelMode.Disabled;
            settings.ClientSideEvents.BeginCallback = "function (s,e) { lp.Show(); }";
            settings.ClientSideEvents.EndCallback = "function (s,e) { lp.Hide(); }";

            settings.CommandColumn.Visible = true;
            settings.CommandColumn.ShowNewButton = false;
            settings.CommandColumn.ShowNewButtonInHeader = true;
            settings.CommandColumn.ShowDeleteButton = true;
            settings.CommandColumn.ShowEditButton = true;
            settings.CommandColumn.FixedStyle = GridViewColumnFixedStyle.Left;
            settings.CommandColumn.Width = Unit.Percentage(10);
            settings.CommandColumn.Caption = " ";

            settings.Columns.Add(c =>
            {
                c.FieldName = "IdModuloProgramacion";
                c.Caption = Resources.DocumentoResource.captionProgramacionModulo;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.Width = Unit.Percentage(60);
                c.EditorProperties().ComboBox(p =>
                {
                    p.TextField = "Nombre";
                    p.ValueField = "IdModulo";
                    p.ValueType = typeof(long);
                    p.DataSource = Metodos.GetModulosPrincipalesEmpresa().Where(x => x.CodigoModulo < 11).ToList();
                });
            });
            settings.Columns.Add(c =>
            {
                c.FieldName = "FechaInicio";
                c.Caption = Resources.DocumentoResource.captionProgramacionFechaInicio;
                c.ColumnType = MVCxGridViewColumnType.DateEdit;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                c.Width = Unit.Percentage(10);
            });
            settings.Columns.Add(c =>
            {
                c.FieldName = "FechaFinal";
                c.Caption = Resources.DocumentoResource.captionProgramacionFechaFinal;
                c.ColumnType = MVCxGridViewColumnType.DateEdit;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                c.Width = Unit.Percentage(10);
            });
            settings.Columns.Add(c =>
            {
                c.FieldName = "IdTipoFrecuencia";
                c.Caption = Resources.DocumentoResource.captionFrecuencia;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                c.Width = Unit.Percentage(10);
                c.EditorProperties().ComboBox(p =>
                {
                    p.TextField = "Descripcion";
                    p.ValueField = "Id";
                    p.ValueType = typeof(long);
                    p.DataSource = Metodos.GetPMTTipoFrecuencia();
                });
            });
            settings.Columns.Add(c =>
            {
                c.FieldName = "statusMantenimiento";
                c.Caption = Resources.DocumentoResource.captionStatusMantenimiento;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                c.Width = Unit.Percentage(10);
                c.SetDataItemTemplateContent(dc =>
                {
                    bool _status = bool.Parse(DataBinder.Eval(dc.DataItem, "statusMantenimiento").ToString());
                    if (_status)
                        ViewContext.Writer.Write("<img src=\"../../Content/images/boton_Verde.jpg\" width=\"20\" height=\"20\" />");
                    else
                        ViewContext.Writer.Write("<img src=\"../../Content/images/Boton_rojo.png\" width=\"20\" height=\"20\" />");
                });
            });
            settings.Columns.Add(c =>
            {
                c.FieldName = "statusDocumento";
                c.Caption = Resources.DocumentoResource.captionStatusDocumento;
                c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                c.HeaderStyle.Wrap = DefaultBoolean.True;
                c.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                c.Width = Unit.Percentage(10);
                c.SetDataItemTemplateContent(dc =>
                {
                    bool _status = bool.Parse(DataBinder.Eval(dc.DataItem, "statusDocumento").ToString());
                    if (_status)
                        ViewContext.Writer.Write("<img src=\"../../Content/images/boton_Verde.jpg\" width=\"20\" height=\"20\" />");
                    else
                        ViewContext.Writer.Write("<img src=\"../../Content/images/Boton_rojo.png\" width=\"20\" height=\"20\" />");
                });
            });

            settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.WindowCenter;
            settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.WindowCenter;
            settings.SettingsPopup.EditForm.Modal = true;
            settings.SettingsPopup.EditForm.ShowCloseButton = false;
            settings.SettingsPopup.EditForm.ShowHeader = true;
            settings.SettingsText.PopupEditFormCaption = Resources.DocumentoResource.captionProgramacion;

            settings.SetEditFormTemplateContent(c =>
            {
                Html.DevExpress().FormLayout(fls =>
                {
                    fls.Name = "FormLayoutProgramaciones";
                    fls.Width = Unit.Percentage(100);
                    fls.ColCount = 2;

                    fls.Items.Add(i =>
                    {
                        i.FieldName = "IdModuloProgramacion";
                        i.Caption = Resources.DocumentoResource.captionProgramacionModulo;
                        i.ColSpan = 2;
                        i.NestedExtension().ComboBox(s =>
                        {
                            s.Width = Unit.Percentage(100);
                            s.Properties.TextField = "Nombre";
                            s.Properties.ValueField = "IdModulo";
                            s.Properties.ValueType = typeof(long);
                            s.Properties.DataSource = Metodos.GetModulosPrincipalesEmpresa().Where(x => x.CodigoModulo < 11).ToList();
                            s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
                            s.ShowModelErrors = true;
                        });
                    });
                    fls.Items.Add(i =>
                    {
                        i.FieldName = "FechaInicio";
                        i.Caption = Resources.DocumentoResource.captionProgramacionFechaInicio;

                        i.NestedExtension().DateEdit(s =>
                        {
                            string UserTimeZone = Session["UserTimeZone"].ToString();
                            int Horas = int.Parse(UserTimeZone.Split(':').First());
                            int Minutos = (Math.Abs(Horas) * 60) + int.Parse(UserTimeZone.Split(':').Last());
                            if (Horas < 0) Minutos *= -1;

                            s.Properties.MinDate = DateTime.UtcNow.AddMinutes(Minutos);
                            s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
                            s.Properties.ClientSideEvents.DateChanged = "InicioChanged";
                            s.ShowModelErrors = true;
                            s.Width = Unit.Percentage(100);
                        });
                    });
                    fls.Items.Add(i =>
                    {
                        i.FieldName = "FechaFinal";
                        i.Caption = Resources.DocumentoResource.captionProgramacionFechaFinal;
                        i.NestedExtension().DateEdit(s =>
                        {
                            string UserTimeZone = Session["UserTimeZone"].ToString();
                            int Horas = int.Parse(UserTimeZone.Split(':').First());
                            int Minutos = (Math.Abs(Horas) * 60) + int.Parse(UserTimeZone.Split(':').Last());
                            if (Horas < 0) Minutos *= -1;

                            s.Properties.MinDate = DateTime.UtcNow.AddMinutes(Minutos);
                            s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
                            s.ShowModelErrors = true;
                            s.Width = Unit.Percentage(100);
                        });
                    });
                    fls.Items.Add(i =>
                    {
                        i.FieldName = "IdTipoFrecuencia";
                        i.Caption = Resources.DocumentoResource.captionFrecuencia;
                        i.ColSpan = 2;
                        i.NestedExtension().ComboBox(s =>
                        {
                            s.Width = Unit.Percentage(100);
                            s.Properties.TextField = "Descripcion";
                            s.Properties.ValueField = "Id";
                            s.Properties.ValueType = typeof(long);
                            s.Properties.DataSource = Metodos.GetPMTTipoFrecuencia();
                            s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
                            s.ShowModelErrors = true;
                        });
                    });

                    fls.Items.Add(i =>
                    {
                        i.ColSpan = 2;
                        i.ShowCaption = DefaultBoolean.False;
                    }).SetNestedContent(() =>
                    {
                        ViewContext.Writer.Write("<div style='float:right'>");
                        Html.DevExpress().Button(
                            btnSettings =>
                            {
                                btnSettings.Name = "btnUpdate";
                                btnSettings.Text = Resources.BCMWebPublic.captionButtonSave;
                                btnSettings.ClientSideEvents.Click = "function(s, e){ gvProgramacion.UpdateEdit(); }";
                            }).Render();
                        Html.DevExpress().Button(
                            btnSettings =>
                            {
                                btnSettings.Name = "btnCancel";
                                btnSettings.Text = Resources.BCMWebPublic.captionButtonCancel;
                                btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                                btnSettings.ClientSideEvents.Click = "function(s, e){ gvProgramacion.CancelEdit(); }";
                            }).Render();
                        ViewContext.Writer.Write("</div>");
                    });
                    fls.Items.AddEmptyItem();
                })
                    .Bind(ViewData["EditableProgramacion"] ?? c.DataItem)
                    .Render();
            });

            settings.InitNewRow = (s, e) =>
            {
                string UserTimeZone = Session["UserTimeZone"].ToString();
                int Horas = int.Parse(UserTimeZone.Split(':').First());
                int Minutos = (Math.Abs(Horas) * 60) + int.Parse(UserTimeZone.Split(':').Last());
                if (Horas < 0) Minutos *= -1;

                DateTime _startDate = DateTime.UtcNow.AddMinutes(Minutos);

                e.NewValues["FechaInicio"] = _startDate.AddDays(1);
                e.NewValues["FechaFinal"] = _startDate.AddDays(30);
                e.NewValues["IdModuloProgramacion"] = null;
                e.NewValues["IdTipoActualizacion"] = 1;
                e.NewValues["IdTipoFrecuencia"] = null;

            };
        });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Metodos.GetProgramaciones()).GetHtml()

BCMWeb/Views/PMT/ProgramacionUsuariosPartialView.cshtml
@using BCMWeb
@using DevExpress.Data;

@Html.DevExpress().GridView(settings =>
{
    settings.Name = "gvProgramacionUsuario";
    settings.KeyFieldName = "IdProgramacion;IdUsuario";
    settings.CallbackRouteValues = new { Controller = "PMT", Action = "ProgramacionUsuariosPartialView", Model };
    settings.Width = Unit.Percentage(100);
    settings.Settings.VerticalScrollableHeight = 225;
    settings.Settings.HorizontalScrollBarMode = ScrollBarMode.Hidden;
    settings.Settings.VerticalScrollBarMode = ScrollBarMode.Auto;
    settings.SettingsPager.Mode = GridViewPagerMode.ShowAllRecords;
    settings.SettingsLoadingPanel.Mode = GridViewLoadingPanelMode.Disabled;

    settings.CommandColumn.Visible = true;
    settings.CommandColumn.Caption = " ";
    settings.CommandColumn.ShowSelectCheckbox = true;
    settings.CommandColumn.SelectAllCheckboxMode = GridViewSelectAllCheckBoxMode.AllPages;
    settings.CommandColumn.Width = Unit.Percentage(10);
    settings.CommandColumn.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
    settings.CommandColumn.CellStyle.HorizontalAlign = HorizontalAlign.Center;

    settings.Columns.Add(c =>
    {
        c.FieldName = "Nombre";
        c.Caption = Resources.DocumentoResource.captionResponsable;
        c.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
        c.HeaderStyle.Wrap = DefaultBoolean.True;
        c.Width = Unit.Percentage(55);
    });

}).Bind(Model.Usuarios).GetHtml()